adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: clds_productkind
adx_entityname: Product Kind Permission
adx_entitypermission_webrole:
- 2e4a9a7d-d541-ec11-8c62-0022483bead5
adx_entitypermissionid: ffa7ee57-9662-ec11-8f8e-000d3a8474f3
adx_read: true
adx_scope: 756150000
adx_write: false
