adx_calendar_enabled: false
adx_entitylistid: 7a71f8ac-8553-ec11-8f8e-000d3ae9a369
adx_entityname: product
adx_entitypermissionsenabled: true
adx_filter_enabled: false
adx_idquerystringparametername: id
adx_map_distancevalues: 5,10,25,50,100
adx_map_enabled: false
adx_map_infoboxoffsetx: 25
adx_map_infoboxoffsety: 46
adx_map_pushpinheight: 39
adx_map_pushpinwidth: 32
adx_map_resturl: https://dev.virtualearth.net/REST/v1/Locations
adx_map_zoom: 12
adx_name: Product
adx_odata_enabled: false
adx_odata_view: 44aeb57e-840f-4026-b898-24b261493c3c
adx_pagesize: 10
adx_searchenabled: false
adx_view: 44aeb57e-840f-4026-b898-24b261493c3c
adx_views: >-
  {

    "Type": "ViewMetadata",

    "Views": [

      {

        "Type": "View",

        "ViewId": "44aeb57e-840f-4026-b898-24b261493c3c",

        "DisplayName": [

          {

            "Type": "LanguageResources",

            "LCID": 1033,

            "Value": ""

          },

          {

            "Type": "LanguageResources",

            "LCID": 1036,

            "Value": ""

          },

          {

            "Type": "LanguageResources",

            "LCID": 1040,

            "Value": ""

          },

          {

            "Type": "LanguageResources",

            "LCID": 1043,

            "Value": ""

          }

        ]

      }

    ]

  }
