- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 4
  adx_displaypagechildlinks: false
  adx_name: Dairy and Eggs
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 0e192f29-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 14
  adx_displaypagechildlinks: false
  adx_name: Kitchenware
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 1af788eb-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 12
  adx_displaypagechildlinks: false
  adx_name: Frozen
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 20120dcd-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 7
  adx_displaypagechildlinks: false
  adx_name: Sauces and Spices
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 327a7a5d-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 2
  adx_displaypagechildlinks: false
  adx_name: Bakery
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 37b43510-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 1
  adx_displaypagechildlinks: false
  adx_name: Special offers
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 382b7303-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 15
  adx_displaypagechildlinks: false
  adx_name: Special offers
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 4e5f0512-ea5d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 11
  adx_displaypagechildlinks: false
  adx_name: Packets, Cereals and Poultry
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: 770a88b3-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 8
  adx_displaypagechildlinks: false
  adx_name: Canned Food and Oil
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: b172e870-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 3
  adx_displaypagechildlinks: false
  adx_name: Fruits and Vegetables
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: b404c01c-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 9
  adx_displaypagechildlinks: false
  adx_name: Alcoholic Beverages
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: c4997680-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 5
  adx_displaypagechildlinks: false
  adx_name: Meat and Poultry
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: c79dee3c-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 10
  adx_displaypagechildlinks: false
  adx_name: Soft Drinks and Juice
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: c7de3893-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 6
  adx_displaypagechildlinks: false
  adx_name: Fish and Seafood
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: efccc649-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
- adx_disablepagevalidation: false
  adx_displayimageonly: false
  adx_displayorder: 13
  adx_displaypagechildlinks: false
  adx_name: Personal hygiene
  adx_openinnewwindow: false
  adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
  adx_robotsfollowlink: true
  adx_weblinkid: fe1d53df-e75d-ec11-8f8e-000d3a845c50
  adx_weblinksetid: 22adfce9-e65d-ec11-8f8e-000d3a845c50
