adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: prod-map.png
adx_parentpageid: 72a8b4fc-0743-ec11-8c62-0022483bead5
adx_partialurl: prod-map.png
adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
adx_webfileid: a162334e-6046-ec11-8c62-000d3ae89ecf
annotationid: 9a7eea5a-7560-23d2-8e0e-891551f9e0b5
filename: prod-map.png
isdocument: true
mimetype: image/png
objectid: a162334e-6046-ec11-8c62-000d3ae89ecf
objecttypecode: adx_webfile
