adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: prod-img.jpg
adx_parentpageid: 72a8b4fc-0743-ec11-8c62-0022483bead5
adx_partialurl: prod-img.jpg
adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
adx_webfileid: 4e6d2b19-6046-ec11-8c62-000d3ae89ecf
annotationid: 44a4b1c5-ead7-01a5-a7b4-afde8d0101f5
filename: prod-img.jpg
isdocument: true
mimetype: image/jpeg
objectid: 4e6d2b19-6046-ec11-8c62-000d3ae89ecf
objecttypecode: adx_webfile
