adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: prod-img2.jpg
adx_parentpageid: 72a8b4fc-0743-ec11-8c62-0022483bead5
adx_partialurl: prod-img2.jpg
adx_publishingstateid: fe499a7d-d541-ec11-8c62-0022483bead5
adx_webfileid: a7e2e7da-8248-ec11-8c62-000d3ae89ecf
annotationid: 0543099e-9c2c-c83f-81e4-8a228935abfb
filename: prod-img2.jpg
isdocument: true
mimetype: image/jpeg
objectid: a7e2e7da-8248-ec11-8c62-000d3ae89ecf
objecttypecode: adx_webfile
